### ISSUE TITLE
[Linux] Capture Area/Multi-Monitor Issue

### ISSUE THREAD

**Issue by EnragedN3wb** [ZeroxyDev/MonTally#8]
First of all... Thank you so much for bringing this to Linux! I've only been using Linux for about a year, so my expertise is a bit limited, but I'd be happy to help with testing in any way I can! There are a few things I've noticed so far:

1.) The capture area starts on the wrong monitor. The main window starts on my main monitor, but the capture area is starting on the monitor to the left of my main monitor. It works as long as I leave it on that monitor & move my game window there, but if I move the capture area from that monitor it no longer seems to work.

2.) The main window is REALLY tiny on a 4K monitor. I tried using GDK_DPI_SCALE=2.0 but it only seems to scale everything inside the window & not the window itself, which makes a lot of the text get cut-off. I'd suggest either a sliding scale, or options for 1.5x & 2.0x scale for 1440p & 4K resolutions(assuming the default is designed around 1080p).

Operating System: CachyOS Linux 
KDE Plasma Version: 6.3.4
KDE Frameworks Version: 6.13.0
Qt Version: 6.9.0
Kernel Version: 6.12.0-rc1-2-cachyos-rc-lto (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 3700X 8-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon RX 6800 XT
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7B79
System Version: 2.0

**Comment by ZeroxyDev** [comment]
Hey!

First of all, huge thanks for your feedback and for offering to help with testing, it really means a lot!

About the capture area issue: I’m already working on an automatic monitor detection system for the CaptureArea, along with a special Pokémon dialog and a few other improvements. This should be fully fixed in the next update.

Regarding the window scaling: your suggestion makes perfect sense, and it’s definitely something I’m planning to add in the near future.

Thanks again for your feedback!

**Comment by ZeroxyDev** [comment]
I just implemented multi-monitor functionality in the new version (2.2.1). This should resolve any issues with multiple monitors.

You can download it, [[DOWNLOAD HERE]](https://github.com/ZeroxyDev/MonTally/releases/latest)

**Comment by EnragedN3wb** [comment]
Hmm, I just got home & started testing. I see the monitor number at the bottom of the capture area window now & it changes monitor # when I move it, but it still won't detect encounters on my main monitor(monitor 0). 

Even weirder is that if I move the capture area to my right-side monitor, it works. So it works on the left(monitor 1), Works on the right(monitor 2), but won't detect anything on my main monitor in the middle(monitor 0). lol

Any ideas what might be the reason? o.o

**Comment by ZeroxyDev** [comment]
Hey, this seems like a strange issue. I've been testing MonTally on multiple 1080p monitors and haven't had any problems. The fact that it works on your two secondary monitors but not the main one (monitor 0) might be related to the high resolution. 4K resolutions can sometimes cause issues with OCR detection.

Could you let me know the resolutions of all your monitors so I can better understand what's going on?

In the meantime, could you try the following:

Only select the area where the Pokémon appear in the capture area.

Do a detection test by opening a Notepad, typing in a Pokémon name (like "Deino"), and zooming in on the word so it’s clearly visible.

Set the capture area on that word and try detection.

After that, minimize the Notepad for about 4 seconds and then open it again to finish the simulated battle cycle.

If this works and MonTally detects the Pokémon, it means the detection system is working correctly. The issue would likely be related to the 4K resolution on your main monitor.

Let me know how it goes, and send me the resolutions of your monitors so I can help troubleshoot further.

**Update**: I've noticed that in the code related to the main monitor, it was handled in a special way. I modified the code to detect all monitors equally, so this could potentially cause issues on some systems. (However, I did test it earlier and it was working fine, but with these changes, there shouldn't be any issues related to the correct detection of the capture area regardless of the monitor).

Tomorrow I will release a new update with these changes.

**Comment by EnragedN3wb** [comment]
Okay, so my monitors are 4K(monitor 1), 4K(monitor 0), & 1080p(monitor 2). The first 2 are the same exact brand & model, & the 3rd is an old monitor I just use for Discord & system info:
![Image](https://github.com/user-attachments/assets/a2056723-fccf-459a-88e2-7bdf41d9f383)

I can't seem to get it to detect text in a text editor on any of my monitors, but it's very consistent at detecting the encounters with the game on monitors 1 & 2. xD

Edit: Oh, okay.  Just saw your update & looking forward to testing the changes when they are ready! :)

**Comment by ZeroxyDev** [comment]
I've just compiled the version with the improvements. Let me know if it detects the Pokémon correctly so I can release the update to the general public tomorrow, or if I should keep searching for a solution.

Thanks for taking the time to help improve MonTally.

MonTally 2.2.2 (Beta test) [https://drive.google.com/file/d/1RTurxMp-JeFaLyHRrnj3VfASwwalS1_V/view?usp=sharing](https://drive.google.com/file/d/1RTurxMp-JeFaLyHRrnj3VfASwwalS1_V/view?usp=sharing)

**Comment by EnragedN3wb** [comment]
Success! The capture area defaults to my main monitor & is detecting encounters on all 3 monitors now, yay! :D

Thanks so much for taking the time to work this out with me, & please let me know if you need any more testing done for Linux. It feels very rare that people care about us Linux users with apps like this, so I'm always willing to help any way I can! :P

**Comment by ZeroxyDev** [comment]
Thank you so much for helping me test it on Linux and in 4K! I really appreciate your time. I know how frustrating it can be not having apps like this on Linux, and as a user of both Windows (mainly) and Linux when traveling, I understand how important it is to make MonTally cross-platform.

Although MonTally started as a personal hobby project, born from my own needs, it quickly caught the attention of the community, and I always try to give my best to make it the best tool possible for shiny hunters, no matter which Pokémon game they’re playing.

Thanks again for all your help, and feel free to reach out if you need anything!
